import Head from "next/head";
import { 
  FaJava,
  FaNodeJs
} from 'react-icons/fa';
import {
  AiFillDribbbleCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillHtml5,
} from "react-icons/ai";
import {BiMedal} from "react-icons/bi"
import {
  RiFolderSettingsLine, 
  RiReactjsFill,
} from "react-icons/ri"
import {
  SiCss3, 
  SiTailwindcss, 
  SiJavascript, 
  SiTypescript, 
  SiFigma, 
  SiAdobexd, 
  SiGithub,
  SiAdobephotoshop,
} from "react-icons/si"
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import me from '../public/me.jpg'
import port1 from "../public/portfolio1.png"
import port2 from "../public/gitf.png"
import port3 from "../public/step.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Gabriel Araújo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-gray-100 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section >
          <nav className="py-8 mb-10 flex justify-between dark:text-white">
          <Image src="/../public/icon.png" alt="/" width='80' height='80'/>
            {/* <h1 className="font-burtons text-xl"> Gabriel Araújo</h1> */}
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-[#551498] text- to-[#9e4ff0] text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Cúrriculo
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex items-center justify-evenly">
            <div className="grid justify-items-center">
            <h2 className="text-5xl py-2 text-[#551498] hover:text-[#9e4ff0] md:text-6xl font-bold">
              Gabriel Araújo
            </h2>          
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Frontend e Designer.
            </h3>       
            {/* <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Com foco em ReactJS, mas também com mente para o Designer UX/UI
            </p>         */}
            <div className="text-3xl flex justify-center gap-10 py-3 dark:text-[#9e4ff0] ">
            <a href="https://linkedin.com/in/gabrieln96" target="_blank" rel="noreferrer" > <AiFillLinkedin className="text-[#551498] hover:text-[#9e4ff0]"/> 
            </a>
            <a href="https://github.com/gabrieln96" target="_blank" rel="noreferrer">         <AiFillGithub className="text-[#551498] hover:text-[#9e4ff0]"/>
            </a>
            <a href="https://dribbble.com/gabrihell" target="_blank" rel="noreferrer">
            <AiFillDribbbleCircle className="text-[#551498] hover:text-[#9e4ff0]"/>
            </a>
            </div>
            </div>
            <div className=" bg-gradient-to-b from-[#551498] rounded-full w-80 h-80 relative overflow-hidden md:h-96 md:w-96">
              <Image src={deved} layout="fill" alt="/" objectFit="cover" />
            </div>
          </div>
            <div className="ml-auto mr-auto border max-w-5xl mt-8  dark:opacity-40  ">
            </div>
        </section>
        <section >
          <div className="flex items-center justify-center mt-8">
            <h2 className=" text-4xl py-2 text-[#551498] dark:text-[#9e4ff0]  font-bold sm:text-2xl">
            Quem Sou Eu?
            </h2>
            </div>
            {/* <div className="flex items-center justify-center">
            <h5 className="text-5xl text-[#551498] font-medium dark:text-[#9e4ff0] md:text-2xl">Sobre mim</h5>
            </div> */}
          <div className=" mt-12 mx-72 grid grid-cols-3 place-items-center">
            <div className="rounded-large w-80 h-80 rotate-12 overflow-hidden hover:rotate-0 h-90 w-90 ">
            <Image src={me} layout="fill" alt="/" objectFit="cover" />
            </div>
              <div className="grid gap-8 dark:text-gray-200">
                <div className=" grid justify-items-center border-none rounded-md p-4  text-gray-200 bg-[#551498] hover:bg-[#9e4ff0]">
                  <BiMedal className="w-8 h-8"/>
                  <h5 >Experiência</h5>
                  <small>1+ anos</small>
                </div>
                <div className="grid justify-items-center border-none rounded-md p-4 text-gray-200 bg-[#551498] hover:bg-[#9e4ff0]">
                  <RiFolderSettingsLine className="w-8 h-8"/>
                  <h5>Projetos</h5>
                  <small>4+ Completos</small>
                </div>
              </div>
              <div className="text-base text-justify text-gray-800 dark:text-gray-200 "> 
                <h4>Bracharel em Ciência da Computação, desenvolvedor Front-end e Designer! Desenvolvedor com foco em HTML, CSS, Tailwind, ReactJs, JavaScript e TypeScript. </h4>
                <div className="mt-8">
                <a
                  className="bg-gradient-to-r from-[#551498] text- to-[#9e4ff0] text-white px-4 py-2 border-none rounded-md "
                  href="#"
                >
                  Cúrriculo
                </a>
                </div>
              </div>
          </div>
        </section>
            <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40  ">
            </div>
            <section>
            <div className="flex items-center justify-center mt-8">
            <h2 className=" text-4xl py-2 text-[#551498] dark:text-[#9e4ff0]  font-bold sm:text-2xl">
            Habilidades
            </h2>
            </div>
            <div className=" grid grid-cols-2 place-items-center mx-60 mt-8 ">
            <div className="border-none rounded-3xl text-gray-200 bg-[#551498] hover:bg-[#9e4ff0] ">
                <div className="text-center mt-8 text-2xl font-bold">
                  <h5>Frontend</h5>
                </div>
                <div  className="mt-6 grid grid-cols-3 gap-10 px-10 py-10">
              <div>
                <AiFillHtml5 className="w-8 h-8 "/>
                <h5 className="font-semibold mt-2">HTML</h5>
                <h2 className="opacity-70 italic">Experiente</h2>
              </div>
              <div>
                <SiCss3 className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">CSS</h5>
                <h2 className="opacity-70 italic">Experiente</h2>
              </div>
              <div>
                <SiJavascript className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">JavaScript</h5>
                <h2 className="opacity-70 italic">Intermediário</h2>
              </div>
              <div>
                <SiTypescript className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">TypeScript</h5>
                <h2 className="opacity-70 italic">Básico</h2>
              </div>
              <div>
                <RiReactjsFill className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">ReactJs</h5>
                <h2 className="opacity-70 italic">Intermediário</h2>
              </div>
              <div>
                <SiTailwindcss className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Tailwind</h5>
                <h2 className="opacity-70 italic">Intermediário</h2>
              </div>
            </div>
            </div>
            <div className="border-none rounded-3xl text-gray-200 bg-[#551498] hover:bg-[#9e4ff0]">
                <div className="text-center mt-8 text-2xl font-bold">
                  <h5>Outras Habilidades</h5>
                </div>
                <div  className="mt-6 grid grid-cols-3 gap-10 px-10 py-10">
              <div>
                <SiFigma className="w-8 h-8 "/>
                <h5 className="font-semibold mt-2">Figma</h5>
                <h2 className="opacity-70 italic">Avançado</h2>
              </div>
              <div>
                <SiAdobexd className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Adobe XD</h5>
                <h2 className="opacity-70 italic">Avançado</h2>
              </div>
              <div>
                <SiGithub className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Git</h5>
                <h2 className="opacity-70 italic">Intermediário</h2>
              </div>
              <div>
                <FaJava className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Java</h5>
                <h2 className="opacity-70 italic">Básico</h2>
              </div>
              <div>
                <FaNodeJs className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Node</h5>
                <h2 className="opacity-70 italic">Intermediário</h2>
              </div>
              <div>
                <SiAdobephotoshop className="w-8 h-8"/>
                <h5 className="font-semibold mt-2">Photoshop</h5>
                <h2 className="opacity-70 italic">Avançado</h2>
              </div>
            </div>
            </div>
            </div>
            </section>
            <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40  ">
            </div>
            <section>
              <div className="flex items-center justify-center mt-8">
                <h2 className="text-5xl py-2 text-[#551498] dark:text-[#9e4ff0] md:text-2xl font-bold">
                Experiência
              </h2>
              </div>
      
              <div class=" flex items-center justify-center mt-8">
              <div class="flex flex-col md:grid grid-cols-9 mx-auto">
                <div class="flex flex-row-reverse md:contents">
                  
                  <div class="w-full col-start-1 col-end-5 p-2 rounded-xl my-4 ml-auto border border-[#551498] dark:border-[#9e4ff0]">
                    <h3 class="font-semibold text-xl mb-1 dark:text-white">InforGerneses Software</h3>
                    <p class="text-gray-600 italic">Desenvolvedor Front-end </p>
                    <small class="text-gray-600">10/2022 - 02/2023</small>
                  </div>

                  <div class="col-start-5 col-end-6 md:mx-auto relative mr-10">
                    <div class="h-full w-6 flex items-center justify-center">
                      <div class="h-full w-0.5 bg-gray-200 pointer-events-none"></div>
                    </div>

                    <div class="w-6 h-6 absolute top-1/2 -mt-3 border-2 border-[#551498] dark:border-[#9e4ff0] rounded-full bg-gray-100 shadow"></div>
                  </div>
                </div>

                <div class="flex md:contents">
                  <div class="col-start-5 col-end-6 mr-10 md:mx-auto relative">
                    <div class="h-full w-6 flex items-center justify-center">
                      <div class="h-full w-0.5 bg-gray-200 pointer-events-none"></div>
                    </div>

                    <div class="w-6 h-6 absolute top-1/2 -mt-3 border-2 border-[#551498] dark:border-[#9e4ff0] rounded-full bg-gray-100 shadow"></div>
                  </div>

                  <div class="w-full col-start-6 col-end-10 my-4 mr-auto p-2 border border-[#551498] dark:border-[#9e4ff0] rounded-xl">
                    <h3 class="font-semibold text-xl mb-1 dark:text-white">InforGerneses Software</h3>
                    <p class="text-gray-600 italic">Analista de QA</p>
                    <small class="text-gray-600">07/2022 - 10/2022</small>
                  </div>
                </div>

                <div class="flex flex-row-reverse md:contents">
                  <div class="w-full col-start-1 col-end-5 p-2 rounded-xl my-4 ml-auto border border-[#551498] dark:border-[#9e4ff0]">
                  <h3 class="font-semibold text-xl mb-1 dark:text-white">InforGerneses Software</h3>
                    <p class="text-gray-600 italic">Analista de Suporte</p>
                    <small class="text-gray-600">02/2022 - 06/2022</small>
                  </div>

                  <div class="col-start-5 col-end-6 md:mx-auto relative mr-10">
                    <div class="h-full w-6 flex items-center justify-center">
                      <div class="h-full w-0.5 bg-gray-200 pointer-events-none"></div>
                    </div>

                    <div class="w-6 h-6 absolute top-1/2 -mt-3 border-2 border-[#551498] dark:border-[#9e4ff0] rounded-full bg-gray-100 shadow"></div>
                  </div>
                </div>

                <div class="flex md:contents">
                  <div class="col-start-5 col-end-6 mr-10 md:mx-auto relative">
                    <div class="h-full w-6 flex items-center justify-center">
                      <div class="h-full w-0.5 bg-gray-200 pointer-events-none"></div>
                    </div>

                    <div class="w-6 h-6 absolute top-1/2 -mt-3 border-2 border-[#551498] dark:border-[#9e4ff0] rounded-full bg-gray-100 shadow"></div>
                  </div>

                  <div class="w-full col-start-6 col-end-10 my-4 mr-auto p-2 border border-[#551498] dark:border-[#9e4ff0] rounded-xl">
                  <h3 class="font-semibold text-xl mb-1 dark:text-white">Ostensiva Segurança Privada</h3>
                    <p class="text-gray-600 italic">Técnico em Informática</p>
                    <small class="text-gray-600">2020-2022</small>
      </div>
    </div>
    <div class="flex flex-row-reverse md:contents">
                  
                  <div class="w-full col-start-1 col-end-5 p-2 rounded-xl my-4 ml-auto border border-[#551498] dark:border-[#9e4ff0]">
                  <h3 class="font-semibold text-xl mb-1 dark:text-white">Grupo Mateus</h3>
                    <p class="text-gray-600 italic">Jovem Aprendiz</p>
                    <small class="text-gray-600">2016-2017</small>
                  </div>

                  <div class="col-start-5 col-end-6 md:mx-auto relative mr-10">
                    <div class="h-full w-6 flex items-center justify-center">
                      <div class="h-full w-0.5 bg-gray-200 pointer-events-none"></div>
                    </div>

                    <div class="w-6 h-6 absolute top-1/2 -mt-3 border-2 border-[#551498] dark:border-[#9e4ff0] rounded-full bg-gray-100 shadow"></div>
                  </div>
                </div>
  </div>
</div>
            </section>
            <div className="ml-auto mr-auto border max-w-5xl mt-8  dark:opacity-40  ">
            </div>
            <section>
              <div className="flex items-center justify-center mt-8">
              <small className=" dark:text-white opacity-70 ">Meus Projetos</small>
              </div>
            <div className="flex items-center justify-center">
            
                <h2 className="text-5xl py-2 text-[#551498] dark:text-[#9e4ff0] md:text-2xl font-bold">
                Portfólio
              </h2>
              </div>
             <div className="mt-12 mx-64 grid grid-cols-3 gap-4 place-items-center">
              <div className=" rounded-2xl text-gray-200 bg-[#551498] hover:bg-[#9e4ff0] " >
              <div className="flex justify-center p-6 ">
              <Image className="border rounded-md" src={port1} alt="/" objectFit="cover" />
              </div>
                <h1 className="flex text-center text-xl font-bold">
                  Photograpys - Compartilhe suas experiências!
                </h1>
                <div className="flex justify-evenly mt-2 mb-4">
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="https://github.com/gabrieln96/photograpys" target="_blank" rel="noreferrer"> Github</a>
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="https://photograpys.web.app/" target="_blank" rel="noreferrer">Demo</a>
                  </div>
              </div>
              <div className=" rounded-2xl text-gray-200 bg-[#551498] hover:bg-[#9e4ff0]" >
              <div className="flex justify-center p-6 ">
              <Image className="border rounded-md" src={port2} alt="/" objectFit="cover" />
              </div>
                <h1 className="grid grid-rows-2 place-items-center text-xl font-bold">
                  Git Finder
                </h1>
                <div className="flex justify-evenly mt-2 mb-4">
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="https://github.com/gabrieln96/git-finder" target="_blank" rel="noreferrer"> Github</a>
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="">Demo</a>
                  </div>
              </div>  <div className=" rounded-2xl text-gray-200 bg-[#551498] hover:bg-[#9e4ff0] " >
              <div className="flex justify-center p-6 ">
              <Image className="border rounded-md" src={port3} alt="/" objectFit="cover" />
              </div>
                <h1 className="grid grid-rows-2 place-items-center text-xl font-bold">
                  Form MultiStep
                </h1>
                <div className="flex justify-evenly mt-2 mb-4">
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="http://github.com" target="_blank" rel="noreferrer"> Github</a>
                  <a className="border rounded-md py-2 px-5 text-xl font-semi-bold hover:bg-white hover:text-gray-900" href="">Demo</a>
                  </div>
              </div>  
              </div>
            </section>
            <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40  ">
            </div>
      </main>
    </div>
  );
}
