import Head from "next/head";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

import Image from "next/image";

import Header from "./components/Header";
import About from "./components/About";
import Skills from "./components/Skills";
import Experience from "./components/Experience";
import Porfolio from "./components/Porfolio";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
  <div className={darkMode ? "dark" : ""}>
    <Head>
      <title>Gabriel Araújo</title>
        <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <main className=" bg-gray-100 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
    <nav className="py-8 mb-10 flex justify-between dark:text-white">
      <Image src="/../public/icon.png" alt="/" width='80' height='80'/>
      {/* <h1 className="font-burtons text-xl"> Gabriel Araújo</h1> */}
      <ul className="flex items-center">
        <li>
        <BsFillMoonStarsFill
        onClick={() => setDarkMode(!darkMode)}
        className=" cursor-pointer text-2xl"
        />
        </li>
        <li>
        <a className="bg-gradient-to-r from-[#551498] text- to-[#9e4ff0] text-white px-4 py-2 border-none rounded-md ml-8" href="#" >
        Cúrriculo
        </a>
        </li>
      </ul>
    </nav>
  <Header/>
    <div className="ml-auto mr-auto border max-w-5xl mt-8  dark:opacity-40  ">
    </div>
  <About/>
    <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40">
    </div>
  <Skills/>
    <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40  ">
    </div>
  <Experience/>
    <div className="ml-auto mr-auto border max-w-5xl mt-8  dark:opacity-40  ">
    </div>
  <Porfolio/>
    <div className="ml-auto mr-auto border max-w-5xl mt-12  dark:opacity-40  ">
    </div>
  </main>
  </div>
  );
}
